### ISSUE TITLE
Feat: 친구 기능 구현

### ISSUE THREAD

**Issue by ramun2** [PathSnap/PathSnap-BE#111]
### Description

- 단체 기록에서 팀장이 친구를 초대하려 필요한 기능들을 구현하고 단체 기록에서 친구들 리스트가 보이는 기능도 구현

### TODO

- [x] 친구 관련 테이블 수정( User,Record)
- [x] 친구 테이블,서비스,레퍼지토리 구현
- [x] 친구 검색 기능 구현
- [x] 친구 추가 기능 구현
- [x] 친구 리스트 조회 기능 구현
- [x] 친구 삭제 기능 구현
