### ISSUE TITLE
Feat: 개인 기록 기능

### ISSUE THREAD

**Issue by ramun2** [PathSnap/PathSnap-BE#31]
### Description

- userId와 recordlsGroup을 받아 기록id를 반환 

### TODO

- [x] RecordStartController 기능 구현
- [x] RecordStartService 기능 구현
- [x] RecordStartRepository 기능 구현
- [x] UserNotFoundException 예외처리 구현
