### ISSUE TITLE
Feat: 포토 기록 기능 

### ISSUE THREAD

**Issue by ramun2** [PathSnap/PathSnap-BE#37]
### Description

- 포토 기록 저장,수정,삭제 기능 구현

### TODO

- [x] 포토기록 생성 기능 구현
- [x] 포토기록 수정 기능 구현
- [x] 포토기록 삭제 기능 구현
- [x] 이미지관련 Dto 구현
- [x] 예외처리구현
