### ISSUE TITLE
Feat: 기록 상세 조회 기능 구현

### ISSUE THREAD

**Issue by ramun2** [PathSnap/PathSnap-BE#61]
### Description

- 기록 상세 조회, 수정, 삭제 기능 구현

### TODO

- [x] 기록 상세 조회 구현 
- [x] 기록 안에 있는 경로 기록 운송수단 로직 구현
- [x] 기록 삭제 기능 구현
- [x] 예외처리 구현
- [x] 기록안에 있는 포토기록, 경로기록 순서변경 구현
- [x] 기록 이름 수정 구현
